# Generated by Django 5.1 on 2025-01-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='icon',
            new_name='icone',
        ),
    ]
